metaplex-foundation/developer-hub

- src/pages/token-metadata/mint.md
fix misleading imports in examples for creating tokens.
> fix misleading imports in examples for creating tokens

- src/pages/bubblegum/mint-cnfts.md
Bubblegum was changed in https://github.com/metaplex-foundation/mpl-bubblegum/pull/43 to allow collection `verified` field to be passed in as either `true` or `false`.
> Change message on `mintToCollectionV1` to allow verified `true` or `false`

- src/pages/candy-machine/index.md
links in the docs start with `programs` which results in broken links.
> fix (docs): broken links in candy machine docs

- src/pages/candy-machine/index.md
The old link points to the old docs.
> Point JSON Link to developer hub instead of docs.metaplex.com

- src/pages/candy-machine/insert-items.md
The function is not called `nftStorage()` but `nftStorageUploader()`. It also requires a API token.
This change aligns it to the token metadata mint page.
> fix nftStorage snippet

- src/pages/candy-machine/sugar/commands/sign.md
This PR aims to update Sugar's `sign` command documentation. The updated documentation makes users aware that the command relies on a standard gPA call to Metaplex's Token Program (pursuant to [PR #389](https://github.com/metaplex-foundation/sugar/pull/389)). The update emphasizes that such calls can be resource-intensive and might be blocked by some RPC providers
> Update Sign Command Documentation

- src/pages/bubblegum/update-cnfts.md
Just a few minor changes to clarify the usage with the helper method.
https://developer-hub-git-danenbm-update-met-6cf67c-metaplex-foundation.vercel.app/bubblegum/update-cnfts
and you no longer need to pass collection metadata as its now auto-derived from collection mint
> Minor changes to update-metadata examples including one more with helper

- src/pages/bubblegum/index.md
- src/pages/bubblegum/mint-cnfts.md
This just makes it clear what you get back from the parse functions and that you can get the nonce out of the leaf schema.
https://developer-hub-git-danenbm-leaf-from-c622d0-metaplex-foundation.vercel.app/bubblegum/mint-cnfts
> Minor improvement to leaf/asset ID example

- src/pages/token-metadata/token-standard.md
Explorers only show the numbers of the token enum, not the values like `NonFungible`.
Since our docs did not show the translation it is quite confusing for some users.
> Clarification for tokenStandard enum

- src/pages/candy-machine/manage.md
`const collectionUpdateAuthority = generateSigner(umi)` can technically work, but in that case the authority is given to a random wallet that noone has access to.
It also caused users trying to create a CM with an existing collection https://github.com/metaplex-foundation/mpl-candy-machine/issues/58
> use umi.identity as authority

- src/pages/404.md
use all-product-grid instead of product-grid
Fixes the 404 page to look like
instead of the empty
> fix 404 page 

- src/components/products/index.js
- src/components/products/sugar/Hero.jsx
- src/components/products/sugar/Logo.jsx
- src/components/products/sugar/index.js
This adds a link in the dev tools menu section for sugar.
It points to the existing sugar docs, but should make them more visible.
> Add sugar link in Dev Tools

- src/components/Header.jsx
Found it inconvenient for the github link in the header to redirect within the same tab, as I was usually reading docs and wanting to goto github to look at some source code without losing my place.
> Make github header link open in new tab

- src/pages/token-metadata/mint.md
Some users got confused on how to change the decimals. Especially for decimals 0 you have to use some. Otherwise the JS validation fails internally and it uses 9 instead because of this:
> Add decimal example on mint

- src/pages/bubblegum/verify-collections.md
- src/pages/candy-machine-4/index.md
- src/pages/candy-machine-4/sugar/bring-your-own-uploader.md
- src/pages/candy-machine-4/sugar/installation.md
- src/pages/candy-machine/index.md
- src/pages/candy-machine/sugar/bring-your-own-uploader.md
- src/pages/candy-machine/sugar/installation.md
Some images were still included from docs.metaplex.com.
Some links pointed to docs.metaplex.com still.
This PR fixes it.
> Fix old docs images and links

- src/pages/candy-machine/guards/token2022-payment.md
when minting the user should specify that it is a `token2022Payment` and not a `tokenPayment` otherwise it will pass the token22 ID and it will throw an error
> docs(token2022PaymentGuard): fix minting code block

- src/pages/core/core-js-sdk-v1-0.md
there is a small type on the text whether at some places its been typed as wether
> Fix typo in core-js-sdk-v1-0 documentation

- src/pages/core/getting-started/rust.md
Quick typo fix on the getting started docs
> Fix typo in "getting started" Rust CPI section

- src/pages/core-candy-machine/mint.md
With Core, I don't think requestion `800_000` compute units is reasonable. 
Remove the paragraph from the basic minting section and introduced it in minting with guards
Reduce initial requested CUs to 300k
Here is the [transaction](https://explorer.solana.com/tx/4nmF8PgkLKFdkJfTmk5yqoRDTFZPtFf87aaguy73cKBVojadvcn3CdA7AKAKXP9kZe83btqpSMLKn8g7BtQmiwvd?cluster=devnet) for a basic mint from a core CM using the sol guard using less that 80k CUs
> candy machine docs changes for cu

- src/pages/bubblegum/mint-cnfts.md
Some users in discord d issues finding this function. Others tried to use it before the tx was finalized.
This should make it a bit more visible and clarify it.
> Bubblegum - clarify lead schema / asset id header

- src/pages/core/fetch.md
To make the DAS Extension more visible I've added it to the fetch page.
> add DAS core extension to core fetch asset page

- src/pages/candy-machine/index.md
> fix CM links

- src/pages/core-candy-machine/create.md
Was incorrect in the core CM guide. Aligned to the V3 Guide based on community Feedback.
> Fix candy machine name and uri lengths

- src/components/products/guides/index.js
- src/pages/core/guides/print-editions.md
- src/pages/guides/translated/japanese.md
* Preview: https://developer-hub-git-danenbm-translated-guides-metaplex-foundation.vercel.app/guides/translated/japanese
* Also fixed link to Core Candy Machine minting page.
> Add links to Japanese guides

- src/pages/token-metadata/collections.md
Users are struggling quite often and think that they can pass in the mint address instead of the metadata PDA. this should clarify it.
> clarify metadata PDA

- src/middleware.js
Keith flagged that the middleware I implemented was spiking Vercel edge data usage since it was rendering on every invocation. 
After reading the Edge Middleware docs, I implemented the config object with a matcher property. 
By adding this piece of code: 
`export const config = {
matcher: ['/umi/:path*'],
};`
Now Next.js will only run the middleware on /umi paths and not on very invocation.
> Updated the Middleware to not trigger on every request

- .vscode/settings.json
- src/pages/bubblegum/burn-cnfts.md
- src/pages/bubblegum/delegate-cnfts.md
- src/pages/bubblegum/transfer-cnfts.md
- src/pages/bubblegum/update-cnfts.md
- src/pages/bubblegum/verify-collections.md
- src/pages/bubblegum/verify-creators.md
```ts
const assetWithProof = await getAssetWithProof(umi, assetId, 
{ truncateCanopy: true }
);
```
to all examples.
> added truncate as default to all getAssetWithProof() examples

- src/pages/umi/getting-started/index.md
Read why, here: https://github.com/solana-labs/solana-web3.js/issues/3498
> Lock to @solana/web3.js 1.x for compatibility

- src/pages/bubblegum/getting-started/js.md
- src/pages/candy-machine/getting-started/js.md
- src/pages/core/getting-started/js.md
- src/pages/guides/javascript/how-to-transfer-sol-on-solana.md
- src/pages/inscription/getting-started/js.md
- src/pages/token-metadata/getting-started/js.md
- src/pages/token-metadata/guides/javascript/create-an-nft.md
- src/pages/umi/getting-started/index.md
> lock web3js at 1

- src/components/products/core/index.js
- src/pages/core/faq.md
- src/pages/core/guides/create-soulbound-nft-asset.md
- src/pages/core/guides/index.md
Provides an overview over the differences of Frozen Soulbound assets and assets with an Oracle that denies transferring.
It uses the default oracle deployed by Tony. Their addresses will be added to the oracle plugin page in an additional PR.
Modified Pages:
- https://developer-hub-git-core-soulbound-assets-metaplex-foundation.vercel.app/core/faq (removed the freeze example and point to the quide instead)
- https://developer-hub-git-core-soulbound-assets-metaplex-foundation.vercel.app/core/guides (added the guide to the overview)
- https://developer-hub-git-core-soulbound-assets-metaplex-foundation.vercel.app/core/guides/create-soulbound-nft-asset (the guide itself)
> Soulbound Assets in MPL-Core

- src/components/products/guides/index.js
- src/pages/mpl-hybrid/guides/create-your-first-hybrid-collection.md
I feel like more boilerplate is better here.
Especially because of the required `publicKey as publicKeySerializer` in the import.
> hybrid guide - extend scripts with boilerplate

- src/pages/bubblegum/mint-cnfts.md
- src/pages/umi/transactions.md
1) Highlighting that to parse the leaf from a transaction the tx has to be finalized in [src/pages/bubblegum/mint-cnfts.md](https://developer-hub-git-mark-umitransaction-metaplex-foundation.vercel.app/bubblegum/mint-cnfts)
2) Adding missing packages in [src/pages/bubblegum/mint-cnfts.md](https://developer-hub-git-mark-umitransaction-metaplex-foundation.vercel.app/bubblegum/mint-cnfts)
3) Add example how to serialize a base58 signature back to uint8Array [src/pages/umi/transactions.md](https://developer-hub-git-mark-umitransaction-metaplex-foundation.vercel.app/umi/transactions#convert-transaction-signature-format)
> Transaction finalization and convertion

- pnpm-lock.yaml
- src/components/products/Grid.jsx
- src/components/products/GridAllProducts.jsx
- src/components/products/sugar/index.js
Two things that always appear in the console when building:
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
and 
Invalid href '//candy-machine/sugar' passed to next/router in page: '/404'. Repeated forward-slashes (//) or backslashes \ are not valid in the href.
> fix minor errors

- src/components/products/coreCandyMachine/index.js
- src/pages/core-candy-machine/guides/create-a-core-candy-machine-with-hidden-settings.md
- src/pages/core-candy-machine/guides/index.md
Link to latest deployment:
https://developer-hub-git-andre-core-candy-m-6d7080-metaplex-foundation.vercel.app/core-candy-machine/guides/create-a-core-candy-machine-with-hidden-settings
> Added Core Candy Machine with hidden settings guide

- src/styles/docsearch.css
There was a CSS issue regarding accessability labels in which they were not hidden.
This is in reference to https://github.com/metaplex-foundation/developer-hub/issues/220
Added the css class that was being referenced and hidden the elements.
> fixed accessability label visability for search bar

- src/pages/guides/javascript/how-to-create-a-solana-token.md
Removes nonexistent `createTokenAccountIfMissing` function in example and replaces it with the correct `createTokenIfMissing` function.
Also fixes a few nits related to `publicKey`.
> docs: use correct `createTokenIfMissing` function

- src/pages/candy-machine/guides/airdrop-mint-to-another-wallet.md
- src/pages/candy-machine/guides/mint-to-another-wallet.md
- src/pages/core-candy-machine/fetching-a-candy-machine.md
- src/pages/core-candy-machine/guides/create-a-core-candy-machine-ui.md
- src/pages/core-candy-machine/guides/create-a-core-candy-machine-with-hidden-settings.md
- src/pages/core-candy-machine/preparing-assets.md
- src/pages/core/guides/create-soulbound-nft-asset.md
- src/pages/guides/general/create-deterministic-metadata-with-turbo.md
- src/pages/guides/general/how-to-diagnose-solana-transaction-errors.md
- src/pages/guides/javascript/how-to-add-metadata-to-spl-tokens.md
- src/pages/guides/javascript/how-to-create-a-solana-token.md
- src/pages/guides/javascript/how-to-transfer-sol-on-solana.md
- src/pages/guides/javascript/how-to-transfer-spl-tokens-on-solana.md
- src/pages/guides/templates/metaplex-nextjs-tailwind-template.md
- src/pages/token-metadata/guides/javascript/create-an-nft.md
Adding Aura Endpoints to documentation
> Updating endpoits

- src/pages/core/create-asset.md
Adding the `owner` param in two areas of the create section to clarify to users how to directly mint into in a different wallet. This was requested on discord.
https://developer-hub-git-mintcoretodifferentowner-metaplex-foundation.vercel.app/core/create-asset
> clarify how to set an owner of an core asset on mint

- src/pages/core/guides/print-editions.md
Updating the editions guide to not use deprecated functions
https://developer-hub-git-updateeditionsguide-metaplex-foundation.vercel.app/core/guides/print-editions
> update Core Editions guide to SDK v1 functions

- src/components/products/aura/index.js
Old order was a bit confusing with
- get Asset
- get Asset Proof
- Get Asset Batch
- Get Asset Proof Batch
This changes the order to have it more logically ordered.
> fix order of aura menu

- src/components/MobileNavigation.jsx
- src/components/products/aura/index.js
- src/components/products/index.js
Commented out Aura in navigation components so it's easy to put back and changed it's base category form `Aura` to `Dev Tools`
> moved Aura from top level navigation to Dev Tools category

- src/lib/api/aura/das/getAssestByAuthority.js
- src/lib/api/aura/das/getAsset.js
- src/lib/api/aura/das/getAssetBatch.js
- src/lib/api/aura/das/getAssetsByCreator.js
- src/lib/api/aura/das/getAssetsByGroup.js
- src/lib/api/aura/das/getAssetsByOwner.js
- src/lib/api/aura/das/searchAssest.js
Adds the displayOptions fields that are also currently being implemented into the DAS API SDK
> add displayOptions to Aura API examples

- src/pages/core-candy-machine/guides/create-a-core-candy-machine-ui.md
PR to fix a guide layout from missing closing syntax.
Before: https://developers.metaplex.com/core-candy-machine/guides/create-a-core-candy-machine-ui#create-a-mint-function
After: https://developer-hub-git-fix-ccm-guide-metaplex-foundation.vercel.app/core-candy-machine/guides/create-a-core-candy-machine-ui
> fix guide layout

- markdoc/tags.js
- src/components/apiComponents/apiComponentWrapper.jsx
- src/components/apiComponents/exampleSelector.jsx
- src/components/apiComponents/languageRenderer.jsx
- src/components/apiComponents/languageSelector.jsx
- src/components/products/das-api/index.js
- src/lib/api/aura/das/getNftEditions.js
- src/lib/api/aura/das/getTokenAccounts.js
- src/lib/api/aura/methods.js
- src/pages/das-api/methods/get-nft-editions.md
- src/pages/das-api/methods/get-token-accounts.md
This PR adds 
- docs for two new DAS API endpoints. 
- modifies the playground renderer that can display a "not supported" message for the uni API renderer
- Fixes the endpoint dropdown when the same Example Name is used
Pages affected: https://developer-hub-git-mark-newdasendpoints-metaplex-foundation.vercel.app/das-api/methods/get-nft-editions
https://developer-hub-git-mark-newdasendpoints-metaplex-foundation.vercel.app/das-api/methods/get-token-accounts
> add getTokenAccounts & getNftEditions

- src/pages/amman/pre-made-configs.md
- Updates the Endpoints used in the example configs
- Adds a Core Candy Machine Example config for easier copy & paste
Updated Page: https://developer-hub-git-mark-ammancorecand-496d80-metaplex-foundation.vercel.app/amman/pre-made-configs
> add Amman Core Candy Machine Config

- src/pages/inscription/getting-started/js.md
- src/pages/inscription/write.md
- src/pages/umi/transactions.md
Added help for Inscription contract. Writing data is only possible if the initialization transaction has been finalized.
> Make inscription docs more clear
