src/pages/candy-machine/guards/address-gate.md
src/pages/candy-machine/guards/allow-list.md
src/pages/candy-machine/guards/bot-tax.md
src/pages/candy-machine/guards/freeze-sol-payment.md

this aligns in the diagrams how guards are presented as aligned with Loris.

Align guard format

---

src/pages/bubblegum/concurrent-merkle-trees.md

* Add **Intro**, **Leaf Path**, **Leaf Proof**, **Leaf Validation**, and **Concurrency** sections for Bubblegum Merkle tree guide.
* Link to Preview of specific page updated: https://developer-hub-git-danenbm-bubblegum-merkle-tree-metaplex.vercel.app/bubblegum/concurrent-merkle-trees

Add Concurrent Merkle tree advanced guide for Bubblegum

---

src/components/products/candyMachine/index.js
src/pages/candy-machine/getting-started/index.md
src/pages/candy-machine/guards/allocation.md
src/pages/candy-machine/guards/bot-tax.md
src/pages/candy-machine/guards/end-date.md
src/pages/candy-machine/guards/freeze-sol-payment.md
src/pages/candy-machine/guards/freeze-token-payment.md
src/pages/candy-machine/guards/gatekeeper.md
src/pages/candy-machine/guards/mint-limit.md
src/pages/candy-machine/guards/nft-burn.md
src/pages/candy-machine/guards/nft-gate.md
src/pages/candy-machine/guards/nft-payment.md
src/pages/candy-machine/guards/program-gate.md
src/pages/candy-machine/guards/redeemed-amount.md
src/pages/candy-machine/guards/sol-payment.md
src/pages/candy-machine/guards/start-date.md
src/pages/candy-machine/guards/third-party-signer.md
src/pages/candy-machine/guards/token-burn.md
src/pages/candy-machine/guards/token-gate.md
src/pages/candy-machine/guards/token2022-payment.md
src/pages/candy-machine/references/index.md

Adding the remaining guards - besides allocation. For now diagrams are images instead of nicely programmed ones. Those will be replaced in the future.

Add rest of the guards as image

---

src/pages/bubblegum/index.md
src/pages/bubblegum/stored-nft-data.md

Link to preview of specific page I updated: https://developer-hub-git-danenbm-stored-nft-metaplex.vercel.app/bubblegum/stored-nft-data

Add stored NFT data Bubblegum section

---

src/pages/bubblegum/hashed-nft-data.md
src/pages/bubblegum/index.md

Link to preview of specific updated page: https://developer-hub-git-danenbm-hashed-nft-data-metaplex.vercel.app/bubblegum/hashed-nft-data

Adding Bubblegum guide for hashed NFT data

---

src/pages/bubblegum/concurrent-merkle-trees.md
src/pages/bubblegum/merkle-tree-canopy.md

Link to preview for specific section updated: https://developer-hub-git-danenbm-canopy-metaplex.vercel.app/bubblegum/merkle-tree-canopy

Add Bubblegum canopy section

---

src/pages/candy-machine/guards/address-gate.md
src/pages/candy-machine/guards/allocation.md
src/pages/candy-machine/guards/allow-list.md
src/pages/candy-machine/guards/bot-tax.md
src/pages/candy-machine/guards/end-date.md
src/pages/candy-machine/guards/freeze-sol-payment.md
src/pages/candy-machine/guards/freeze-token-payment.md
src/pages/candy-machine/guards/gatekeeper.md
src/pages/candy-machine/guards/mint-limit.md
src/pages/candy-machine/guards/nft-burn.md
src/pages/candy-machine/guards/nft-gate.md
src/pages/candy-machine/guards/nft-payment.md
src/pages/candy-machine/guards/program-gate.md
src/pages/candy-machine/guards/redeemed-amount.md
src/pages/candy-machine/guards/sol-payment.md
src/pages/candy-machine/guards/start-date.md
src/pages/candy-machine/guards/third-party-signer.md
src/pages/candy-machine/guards/token-burn.md
src/pages/candy-machine/guards/token-gate.md
src/pages/candy-machine/guards/token-payment.md
src/pages/candy-machine/guards/token2022-payment.md

This PR adds the missing guard diagrams which were added as image so far.

Add missing guard diagrams

---

src/pages/token-metadata/getting-started/rust.md
src/pages/token-metadata/mint.md

This PR adds Rust examples to Token Metadata documentation.

Add rust examples to token metadata

---

src/components/products/tokenMetadata/index.js
src/pages/token-metadata/token-2022.md

This PR adds details on how SPL Token-2022 works with Token Metadata.

Add token-2022 page

---

src/pages/bubblegum/mint-cnfts.md

https://developer-hub-git-danenbm-parse-asse-c18c9e-metaplex-foundation.vercel.app/bubblegum/mint-cnfts

Add cNFT examples for parsing leaf ID from mint and mint to collection

---

src/pages/inscription/authority.md
src/pages/inscription/clear.md
src/pages/inscription/close.md
src/pages/inscription/fetch.md
src/pages/inscription/initialize.md
src/pages/inscription/write.md

* clarifies imports
* leverages the dialect switcher
* adds info for authorities
* adds info for fetching

Add additional inscription docs

---

src/components/products/umi/index.js
src/pages/umi/metaplex-umi-plugins.md

Users where getting confused on "where to go next" during their Umi setup process so I've added a Metaplex Umi plugins description page that should benefit new users with an overview of each plugin and also outlined their reprospective jobs/tasks each plugin/program performs to give them a form of direction in which to explore next.
Link is now the 4th option of Introduction in the Umi Menu after 'Connecting to Umi'.

Umi - Added Metaplex Plugins Overview

---

src/pages/candy-machine/guard-route.md
src/pages/candy-machine/mint.md

available-guards is just called guards now

fix guard links

---

src/pages/core/index.md

(first part was accidentally pushed into main directly)

Add Core intro

---

src/components/products/tokenMetadata/index.js
src/pages/token-metadata/collections.md
src/pages/token-metadata/faq.md
src/pages/token-metadata/recipes/get-by-collection.md
src/pages/token-metadata/recipes/index.md

Guide and links referencing it added.
Guide updated to include the superior DAS method.

add get collection guide guide from notion

---

src/pages/token-metadata/burn.md

Make how to burn a NFT in a collection more obvious

burnV1 example for asset in collection

---

src/pages/candy-machine/settings.md

We were lacking an example int the past.

HiddenSettings hash function

---

src/components/products/coreCandyMachine/index.js
src/pages/core-candy-machine/guards/edition.md

Add edition guard link

---

src/pages/core/plugins/addBlocker.md
src/pages/core/plugins/immutableMetadata.md

added both plugins. 
Missing an additional page to explain different core immutability features.

immutableMetadata, addBlocker

---

src/components/products/coreCandyMachine/index.js
src/pages/core-candy-machine/guards/asset-mint-limit.md
src/pages/core-candy-machine/guards/nft-mint-limit.md

should not be merged before https://github.com/metaplex-foundation/mpl-core-candy-machine/pull/5

Add asset mint limit guard

---

src/components/products/coreCandyMachine/index.js
src/pages/core-candy-machine/guards/asset-burn-multi.md
src/pages/core-candy-machine/guards/asset-burn.md
src/pages/core-candy-machine/guards/asset-payment-multi.md
src/pages/core-candy-machine/guards/asset-payment.md

Do not merge before https://github.com/metaplex-foundation/mpl-core-candy-machine/pull/5

Asset Payment and Asset Burn Guards

---

src/pages/core-candy-machine/guards/asset-payment-multi.md

need to pass assets in an array, not just one

Bugfix CMC assetPaymentMulti

---

src/pages/core/burn.md

Number according to @blockiosaurus https://discord.com/channels/848060988636921856/1257834316650647715/1257834316650647715

Clarify SOL amount kept in Account after burn

---

src/pages/core/plugins/index.md

- clarify and make more present information about force approve from pernament plugins

Force Approve Clarification

---

src/pages/candy-machine/sugar/configuration.md

Recently multiple users tried to use hiddenSettings but struggled a bit with the explanation. This makes it a bit more clear.

sugar hidden settings clarification

---

src/pages/core/faq.md

the guide was released some time ago but we missed to update the FAQ to not only show *coming soon*

add immutability faq entry

---

src/pages/umi/metaplex-umi-plugins.md

We missed to add Core in the past.

add core to umi plugin overview

---

src/pages/bubblegum/mint-cnfts.md

adding the comment based on discord feedback

add assetId comment

---

src/pages/toolbox/index.md

fix createLutForTransactionBuilder

---

src/pages/token-metadata/faq.md
src/pages/token-metadata/mint.md
src/pages/umi/public-keys-and-signers.md

It happens quite a lot that people ask how to use createMetadataAccountV3, not knowing of the replacement. Hope this makes it slightly  more clear.
An additional Guide would still make sense from my POV.

Clarify metadata creation + minor umi change

---

src/pages/guides/translated/japanese.md

* Preview: https://developer-hub-git-danenbm-intermedia-f81885-metaplex-foundation.vercel.app/guides/translated/japanese
* CMV3 guide using Sugar
* Oracle trading experience guide
* AppData ticketing example guide

Add CMV3 guide and Intermediate Oracle and AppData guides

---

src/pages/core-candy-machine/preparing-assets.md

docs: update preparing-assets.md

---

src/components/products/coreCandyMachine/index.js
src/pages/core-candy-machine/guards/asset-burn.md
src/pages/core-candy-machine/guards/asset-gate.md
src/pages/core-candy-machine/guards/asset-mint-limit.md
src/pages/core-candy-machine/guards/asset-payment-multi.md
src/pages/core-candy-machine/guards/asset-payment.md
src/pages/core-candy-machine/guards/vanity-mint.md

depends on https://github.com/metaplex-foundation/mpl-core-candy-machine/pull/14

Add assetGate

---

src/pages/bubblegum/mint-cnfts.md

had some people recently trying to use core collections for bubblegum.
This is an attempt to clarify which kind of collections to use.

clarify bubblegum collections

---

src/pages/core-candy-machine/guards/asset-burn-multi.md
src/pages/core-candy-machine/guards/asset-gate.md
src/pages/core-candy-machine/guards/vanity-mint.md

The guards were deployed to mainnet some time ago already

remove devnet warning

---

src/pages/candy-machine/guides/create-an-nft-collection-on-solana-with-candy-machine.md
src/pages/candy-machine/insert-items.md
src/pages/candy-machine/sugar/commands/upload.md
src/pages/candy-machine/sugar/index.md

- fixes a broken link in the sugar guide
- adds a mention of the guide to the sugar index page
- adds mention of example assets in multiple locations

add sugar guide info

---

src/pages/bubblegum/guides/index.md

Added missing bubblegum guides index.js page that was missing.

add bubblegum guides index page

---

src/pages/core-candy-machine/update.md

Thanks to reports on discord fixing this page.

fix updateCandyGuard function

---

src/components/Fence.jsx
src/styles/scrollbar.css

- added max width to code element in a code block to give space to the copy icon.
- fixed ugggllyyyy scrollbar on code block element.

Code Block Fixes

---

src/pages/token-metadata/faq.md

Preview to FAQ page: https://developer-hub-git-danenbm-sb-faq-metaplex-foundation.vercel.app/token-metadata/faq

Add FAQ for soulbound

---

src/components/products/bubblegum/index.js
src/components/products/guides/index.js
src/pages/bubblegum/guides/index.md
src/pages/bubblegum/guides/javascript/how-to-create-1000000-nfts-on-solana.md
src/pages/bubblegum/guides/javascript/how-to-interact-with-cnfts-on-other-svms.md

* Preview for this new guide: https://developer-hub-git-danenbm-bgum-other-svms-metaplex-foundation.vercel.app/bubblegum/guides/javascript/how-to-interact-with-cnfts-on-other-svms
* Add link to Bubblegum program guides in top-level **Guides** section.  Preview here: https://developer-hub-git-danenbm-bgum-other-svms-metaplex-foundation.vercel.app/guides

Add Bubblegum guide for other SVMs

---

src/pages/core-candy-machine/create.md

A very small fix

---

src/pages/umi/transactions.md

New section here: https://developer-hub-git-decode-signature-metaplex-foundation.vercel.app/umi/transactions#get-human-readable-transaction-signature

Umi: add transaction signature example

---

src/pages/hydra/index.md

Changes on https://developer-hub-git-hydra-link-ui-metaplex-foundation.vercel.app/hydra

Hydra: Add hydra.metaplex.com, add umi, update links

---

src/pages/core-candy-machine/mint.md

there are no token accounts in core.

remove token account example

---

src/components/Hero.jsx
src/components/products/aura/Hero.jsx
src/components/products/aura/index.js
src/components/products/index.js
src/pages/aura/batch-minting.md
src/pages/aura/blockchains/eclipse.md
src/pages/aura/blockchains/solana.md
src/pages/aura/faq.md
src/pages/aura/index.md
src/pages/aura/managing-compressed-state.md
src/pages/aura/reading-solana-and-svm-data.md
src/pages/bubblegum/mint-cnfts.md
src/pages/rpc-providers.md
src/styles/accent.css

URL Preview: https://developer-hub-git-tony-aura-docs-metaplex-foundation.vercel.app/aura
* Added the Overview and General Structure
* Added `Economics` and `Create Merkle Tree` pages
* Added Batch Minting Page
* General Quality Improvement of Readability and Text
* Added the `data-availability-and-decentralized-indexing` page
* Added `spam-prevention` paragraph to `batch-minting` page
* merged `create-merkle-tree` and `batch-minting`
* Added the accent for Aura
* `staking` page done
* General fixes
* Fixed the code example and explaination for `batch_minting`. Missing the upload and a double check on the collection stuff
* General Fixes
* Added Notes regarding Collection in `batch_minting`
* Added `faq` page and general fixes
* reverted color back to pink gradient. Added SDK pages. Added …

Danenbm/aura/docs v0.1 (#5)

---

src/pages/core/create-asset.md
src/pages/core/external-plugins/adding-external-plugins.md
src/pages/core/external-plugins/oracle.md
src/pages/core/external-plugins/removing-external-plugins.md

Typos, wrong package names etc.

Core - fix some issues

---

src/components/products/guides/index.js
src/components/products/umi/index.js
src/pages/umi/guides/index.md
src/pages/umi/guides/optimal-transactions-with-compute-units-and-priority-fees.md
src/pages/umi/toolbox/priority-fees-and-compute-managment.md

Pages changed:
- Guide: https://developer-hub-git-umi-prio-fees-metaplex-foundation.vercel.app/umi/guides/optimal-transactions-with-compute-units-and-priority-fees
- Callout added to the toolbox docs: https://developer-hub-git-umi-prio-fees-metaplex-foundation.vercel.app/umi/toolbox/priority-fees-and-compute-managment

new optimal prio fees + compute units with umi guide

---

src/pages/bubblegum/guides/index.md
src/pages/bubblegum/guides/javascript/how-to-create-1000000-nfts-on-solana.md
src/pages/bubblegum/update-cnfts.md

**Adjustments**
Updated cNFT UpdateMetadata 
https://developer-hub-git-fix-cnft-guide-metaplex-foundation.vercel.app/bubblegum/update-cnfts
Update Bubblegum Guide Index - 
https://developer-hub-git-fix-cnft-guide-metaplex-foundation.vercel.app/bubblegum/guides
Updated cNFT Guide - 
https://developer-hub-git-fix-cnft-guide-metaplex-foundation.vercel.app/bubblegum/guides/javascript/how-to-create-1000000-nfts-on-solana

adjusted guide to reflect title rather than slug

---

src/components/products/amman/index.js
src/components/products/bubblegum/index.js
src/components/products/candyMachine/Hero.jsx
src/components/products/candyMachine/index.js
src/components/products/das-api/index.js
src/components/products/fusion/index.js
src/components/products/mpl-hybrid/Hero.jsx
src/components/products/tokenAuthRules/Hero.jsx
src/components/products/umi/index.js
src/pages/core-candy-machine/guides/create-a-core-candy-machine-ui.md
src/pages/core/external-plugins/adding-external-plugins.md
src/pages/core/json-schema.md
src/pages/das-api/getting-started.md
src/pages/das-api/methods/get-asset-by-creator.md
src/pages/guides/setup-a-local-validator.md
src/pages/hydra/quick-start.md
src/pages/rpc-providers.md

- Fix broken links.
- aligns casing for "Getting Started"
- fixes duplicate meta descriptions
- fixes duplicate title

Broken links

---

src/pages/core/external-plugins/oracle.md

adding default oracles

---

src/components/products/candyMachine/index.js
src/pages/candy-machine/guards.md
src/pages/candy-machine/guides/airdrop-mint-to-another-wallet.md
src/pages/candy-machine/guides/index.md
src/pages/candy-machine/guides/mint-to-another-wallet.md
src/pages/candy-machine/mint.md

also fixing some code issues in the CM v3 docs

TM CM airdrop guide

---

src/components/apiComponents/apiComponentWrapper.jsx
src/components/apiComponents/languageComponents/javascriptRequestRenderer.jsx
src/components/apiComponents/languageRenderer.jsx

https://developer-hub-git-fix-aura-api-langu-fcd3f0-metaplex-foundation.vercel.app/aura
Fix language renderer

renderer fix

---

src/pages/aura/blockchains/solana.md

https://developer-hub-git-change-add-aura-so-779f86-metaplex-foundation.vercel.app/aura/blockchains/solana
- add aura solana to main docs

add aura solana networks to docs

---

src/components/products/guides/index.js
src/pages/guides/general/payer-authority-pattern.md

https://developer-hub-git-guide-pap-metaplex-foundation.vercel.app/guides/general/payer-authority-pattern

Adding Payer-Authority pattern guide.

---

src/components/products/GridAllProducts.jsx
src/components/products/aura/index.js
src/components/products/index.js

https://developer-hub-git-mark-auraintooverview-metaplex-foundation.vercel.app/programs-and-tools

adding aura to the product overview grid

---

src/pages/core/update.md
src/pages/index.md

This PR
1) adds a section on How to "Change the collection of a Core Asset" https://developer-hub-git-mark-changecollection-metaplex-foundation.vercel.app/core/update#change-the-collection-of-a-core-asset
2) adds a warning that an asset will be removed from a collection when made immutable https://developer-hub-git-mark-changecollection-metaplex-foundation.vercel.app/core/update#change-the-collection-of-a-core-asset
3) fixes a typo in the overall index page. https://developer-hub-git-mark-changecollection-metaplex-foundation.vercel.app/

Change collection example

---

src/components/products/tokenMetadata/index.js
src/pages/token-metadata/guides/anchor/token-claimer-smart-contract.md
src/pages/token-metadata/guides/index.md

Added the Token Claimer Guide with Merkle Tree but without concurrency (Explained the risks of this approach with locking accounts)
Link: https://developer-hub-git-token-claimer-smar-29dce6-metaplex-foundation.vercel.app/token-metadata/guides/anchor/token-claimer-smart-contract

Token Claimer Guide

---

src/pages/core/sdk/index.md

https://developer-hub-git-mark-fix-links-metaplex-foundation.vercel.app/core/sdk

fix core js link on getting started page

---

src/components/products/core/index.js
src/pages/core/execute-asset-signing.md

https://developer-hub-git-core-execute-metaplex-foundation.vercel.app/core/execute-asset-signing

added execute instruction page that outlines execute and asset signing

---

src/lib/api/aura/das/getAssetsByGroup.js

Key and Value were mixed.
Key has to be "collection"
Value the public key

getAssetsByGroup Fix key <-> value

---

src/components/apiComponents/languageComponents/javascriptRequestRenderer.jsx

Fixes a rendering issue with JS on the aura api pages.

fixed aura javascript aura generator

---

src/components/products/das-api/index.js
src/pages/das-api/methods/get-asset-by-creator.md
src/pages/das-api/methods/get-asset-by-group.md
src/pages/das-api/methods/get-asset-by-owner.md
src/pages/das-api/methods/get-asset-proofs.md
src/pages/das-api/methods/get-asset-signatures.md
src/pages/das-api/methods/get-assets.md
src/pages/das-api/methods/index.md
src/pages/das-api/methods/search-assets.md

https://developer-hub-git-mark-new-das-metaplex-foundation.vercel.app/das-api/methods
https://developer-hub-git-mark-new-das-metaplex-foundation.vercel.app/das-api/methods/get-assets
https://developer-hub-git-mark-new-das-metaplex-foundation.vercel.app/das-api/methods/get-asset-proofs
https://developer-hub-git-mark-new-das-metaplex-foundation.vercel.app/das-api/methods/get-asset-signatures
pending https://github.com/metaplex-foundation/digital-asset-standard-api/pull/12

add "new" DAS methods

---

src/pages/token-metadata/guides/account-size-reduction.md

https://developer-hub-git-feat-add-solrip-metaplex-foundation.vercel.app/token-metadata/guides/account-size-reduction

Adding SolRip to resize utils.

---

src/pages/guides/javascript/how-to-add-metadata-to-spl-tokens.md

checked the script again based on hotjar feedback. 
Some imports were missing and the airdrop throwed a top level await error.

fix how-to-add-metadata-to-spl-tokens.md

---

src/pages/token-metadata/burn.md
src/pages/token-metadata/mint.md
src/pages/token-metadata/update.md

Based one some feedback I've added in some Anchor examples of both Burn and Update for Token Metadata.

Added some Anchor examples to TM burn and update.

---

src/pages/aura/pricing.md

- update Aura pricing table
-  Removed USD pricing due to none updating calculation of token price.
https://developer-hub-git-aura-pricing-update-metaplex-foundation.vercel.app/aura/pricing

update aura pricing chart

---

src/pages/candy-machine/manage.md
src/pages/candy-machine/settings.md
src/pages/core-candy-machine/create.md

This adds a node that recommends hidden settings and revealing.
https://developer-hub-git-hiddensettings-metaplex-foundation.vercel.app/candy-machine/manage#create-candy-machines
https://developer-hub-git-hiddensettings-metaplex-foundation.vercel.app/candy-machine/settings#item-settings
https://developer-hub-git-hiddensettings-metaplex-foundation.vercel.app/core-candy-machine/create#config-line-settings

Add hidden settings note

---

src/pages/core-candy-machine/guards.md

Adding missing guards to the available guards list
https://developer-hub-git-updatecorecmguardsection-metaplex-foundation.vercel.app/core-candy-machine/guards#all-available-guards

update guard list

---

src/pages/core/plugins/freeze-delegate.md

Expanded and added some of the Rust examples for Freeze Delegate Plugin.
https://developer-hub-git-plugins-freeze-del-5f254a-metaplex-foundation.vercel.app/core/plugins/freeze-delegate

added rust CPI examples to freeze delegate plugin

---

src/components/products/tokenMetadata/Hero.jsx
src/components/products/tokenMetadata/index.js

heading tag line modified.
Preview URL - https://developer-hub-git-token-metadata-tag-line-metaplex-foundation.vercel.app/token-metadata

changed tm description

---

src/components/products/core/index.js
src/pages/core/guides/loyalty-card-concept-guide.md

**Loyalty Card Concept Guide**
New guide type I wanted to experiment with where we explain the concept of creating a program and what plugins and lifecycles to use to achieve that designed goal without diving into a full example code base.
https://developer-hub-git-guide-loyalty-card-3be136-metaplex-foundation.vercel.app/core/guides/loyalty-card-concept-guide

app data loyalty card concept guide

---

src/pages/token-metadata/guides/account-size-reduction.md

account resize faq updates

---

pnpm-lock.yaml
src/components/apiComponents/apiComponentWrapper.jsx
src/components/apiComponents/endPointSelector.jsx
src/components/apiComponents/languageRenderer.jsx

Removal of API selector in the DAS Playground
https://developer-hub-git-playground-api-metaplex-foundation.vercel.app/das-api/methods/get-asset
Defaults to `https://api.devnet.solana.com` but saves your supplied RPC address to local storage and recalled upon subsequant page visits.

Playground api

---

src/components/apiComponents/exampleSelector.jsx
src/components/products/das-api/index.js
src/lib/api/aura/das/getAsset.js
src/lib/api/aura/das/getAssetProof.js
src/lib/api/aura/das/getSignaturesForAsset.js

- create and added devnet examples to dropdown
- fixed some navigation issues from moving pages over.
https://developer-hub-git-das-playground-dev-baf570-metaplex-foundation.vercel.app/das-api/methods/get-asset

added devnet examples to dropdown

---

src/pages/candy-machine/guides/airdrop-mint-to-another-wallet.md
src/pages/candy-machine/guides/mint-to-another-wallet.md
src/pages/candy-machine/manage.md
src/pages/candy-machine/settings.md

For some reason otherwise a Borsh Error is thrown when using mintV2 later.
Context: https://discord.com/channels/848060988636921856/1357984054053572649/1357984054053572649

add collectionDetails for createNft in CMv3

---

src/components/products/coreCandyMachine/index.js
src/pages/core-candy-machine/anti-bot-protection-best-practices.md
src/pages/core-candy-machine/guides/index.md

preview - https://developer-hub-git-ccm-bot-protection-guide-metaplex-foundation.vercel.app/core-candy-machine/anti-bot-protection-best-practices

add bot protection best practices

---

markdoc/tags.js
src/components/helperComponents/guideIndex.jsx
src/pages/guides/index.md

Added a guide index with selectable tags for basic filtering.
Preview: https://developer-hub-git-guides-guides-index-metaplex-foundation.vercel.app/guides

Program Guide Index

---

src/pages/security.md

Update security audit dates

---

src/pages/core/plugins/transfer-delegate.md

Added additional rust and js examples for Transfer Delegate plugin.
https://developer-hub-git-plugins-transfer-d-d3fe77-metaplex-foundation.vercel.app/core/plugins/transfer-delegate

added more rust examples for transfer delegate plugin

---

src/components/products/core/index.js
src/pages/core/execute-asset-signing.md
src/pages/core/plugins/freeze-execute.md

New Page for the Plugin: https://developer-hub-git-mark-freezeexecute-metaplex-foundation.vercel.app/core/plugins/freeze-execute
Modified execute page to reference the new Plugin: https://developer-hub-git-mark-freezeexecute-metaplex-foundation.vercel.app/core/execute-asset-signing

Add freezeExecute mpl-core plugin documentation

---

src/pages/core/update.md

Updating the asset collection was coded as the old way. Updated.

fix asset collection update

---

public/llms.txt

Based on the proposal in https://llmstxt.org/ to make the developer hub easier to navigate for llms

add lms.txt

---

src/components/products/cli/index.js
src/pages/cli/core/plugins.md

Corresponding docs for https://github.com/metaplex-foundation/cli/pull/48

add plugin update
